version: '3.8'
services:
  # db:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  
  app:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    # depends_on:
    #   - db
    # environment:
    #   DB_HOST: db
    #   DB_USER: postgres
    #   DB_PASS: postgres
    #   DB_NAME: postgres
    volumes:
      - .:/src
